# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Title (appears only in the PDF properties)
#+AUTHOR: Rayan Raddatz de Matos, Kenichi Brumati, Marcelo Gulart

#+STARTUP: overview indent
#+LANGUAGE: pt-br
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: ACMART
#+LATEX_CLASS_OPTIONS: [format=acmsmall, review=false, screen=true]
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).
# You'll also need to install texlive-publishers to get acmart.cls

* ACM-SMALL configuration for org export + ignore tag (Start Here) :noexport:

#+begin_src emacs-lisp :results output :session :exports both
(add-to-list 'load-path ".")
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
(add-to-list 'org-latex-classes
             '("ACMART"
               "\\documentclass{acmart}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

#+RESULTS:

* *The Paper*                                                       :ignore:
** Latex configurations                                             :ignore:
#+BEGIN_EXPORT latex
% Metadata Information
\acmJournal{Comp. Syst. Perf. Analisys}
%\acmVolume{}
%\acmNumber{}
%\acmArticle{39}
\acmYear{2025}
\acmMonth{12}
%\copyrightyear{2009}
%\acmArticleSeq{9}

% Copyright
%\setcopyright{acmcopyright}
%\setcopyright{acmlicensed}
%\setcopyright{rightsretained}
\setcopyright{none}
%\setcopyright{usgovmixed}
%\setcopyright{cagov}
%\setcopyright{cagovmixed}

% DOI
\acmDOI{0000001.0000001}

% Paper history
%\received{February 2007}
%\received[revised]{March 2009}
%\received[accepted]{June 2009}
#+END_EXPORT
** Frontpage                                                        :ignore:
#+BEGIN_EXPORT latex
\title[Small Title]{Evaluating Tensorflow Parallel Mechanisms for Training of Deep Leaning in a HPC cluster}

\author{Rayan Raddatz de Matos}

\author{Kenichi Brumati}

\author{Marcelo Cardoso Oliveira Gulart}
\affiliation{%
  \institution{Federal University of Rio Grande do Sul}
  \streetaddress{Campus do Vale - Sector 4}
  \city{Porto Alegre}
  \state{RS}
  \postcode{91501-970}
  \country{Brazil}}

#+END_EXPORT
*** Abstract                                                       :ignore:

#+LaTeX: \begin{abstract}

Put the abstract here.

#+LaTeX: \end{abstract}

*** COMMENT ACM Code Classification                                        :ignore:
#+BEGIN_EXPORT latex
%
% The code below should be generated by the tool at
% http://dl.acm.org/ccs.cfm
% Please copy and paste the code instead of the example below.
%
\begin{CCSXML}
<ccs2012>
 <concept>
  <concept_id>10010520.10010553.10010562</concept_id>
  <concept_desc>Computer systems organization~Embedded systems</concept_desc>
  <concept_significance>500</concept_significance>
 </concept>
 <concept>
  <concept_id>10010520.10010575.10010755</concept_id>
  <concept_desc>Computer systems organization~Redundancy</concept_desc>
  <concept_significance>300</concept_significance>
 </concept>
 <concept>
  <concept_id>10010520.10010553.10010554</concept_id>
  <concept_desc>Computer systems organization~Robotics</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
 <concept>
  <concept_id>10003033.10003083.10003095</concept_id>
  <concept_desc>Networks~Network reliability</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
</ccs2012>
\end{CCSXML}

\ccsdesc[500]{Computer systems organization~Embedded systems}
\ccsdesc[300]{Computer systems organization~Redundancy}
\ccsdesc{Computer systems organization~Robotics}
\ccsdesc[100]{Networks~Network reliability}

%
% End generated code
%

#+END_EXPORT

*** Keywords, thanks                                               :ignore:
#+BEGIN_EXPORT latex
\keywords{Deep Learning, HPC, Parallel Training, Distributed Training}
% \thanks{This work is supported by ...}
#+END_EXPORT
*** Maketitle                                                      :ignore:
#+LaTeX: \maketitle

** Introduction

In the last decade, Deep Learning has established itself as the
state-of-the-art for solving complex problems, such as computer vision
and natural language processing. Given the progress in algorithmic
precision, there has been an exponential growth in the complexity of
neural network architectures and the volume of datasets. This scenario
imposes a massive computational load, making the training of robust
models on a single processing unit an difficult task in terms of time
and resources.

To mitigate these challenges, distributed training has become a
standard practice, with an emphasis on the Data Parallelism
strategy. In this approach, a complete replica of the model is
instantiated on each processing unit, and the global
dataset is partitioned into smaller, locally-focused batches. Although
effective, this technique introduces critical synchronization
challenges, as locally calculated gradients must be aggregated and
communicated among all devices at every training step, typically
through All-Reduce operations.

Given this fact, in this work we decided to analyze data parallelism
for AI training using TensorFlow in a HPC cluster to investigate how
the factors related to the application contribute to time reduction in
a parallel scenario.

#+latex: \noindent
*Software and Data Availability*. We endeavor to make our analysis
reproducible for a better science. We made available a companion
material hosted in a public GitHub repository at
#+latex: {\scriptsize\url{https://github.com/kenichi220/comp-sys-perf-analysis-final-work/tree/main}}.
Our companion contains the source code of this article and the
software necessary to handle the created datasets. We also include
instructions to run the experiment and figures.
# An archive is also available in Zenodo at URL.

** Background and Experimental Context
\label{sec.context}
*** Background
\label{sec.background}

TensorFlow is a machine learning system that operates at a large scale
and in heterogeneous \cite{tensorflow2016}. It uses dataflow graphs to
represent the computation, shared state, and the operations that alter
this state.

This architecture maps the nodes of a dataflow graph onto many
machines within a cluster and, within a machine, onto multiple
computational devices (multicore CPUs, GPUs, and TPUs). This offers
flexibility to the developer to experiment with new optimizations and
training algorithms, supporting a variety of applications focused on
deep neural networks. When it comes to distributed training, TensorFlow offers different
strategies with the =tf.distribute.Strategy= API. The TensorFlow
documentations adverts that /"For synchronous training on many GPUs
onmultiple workers, use the tf.distribute.MultiWorkerMirroredStrategy with the Keras Model.fit or a custom training loop."/\cite{distributed}. Meaning for a
distributed training across different nodes in a cluster there is two
options: Using the MultiWorkerMirroredStrategy with the model.fit or
creating a Custom Training Loop by yourself.

*** Experimental Context
In High-Performance Computing (HPC) environments, a highly recommended
practice to access to shared computational resources is to mediate the
access by workload management systems. In our context Slurm (Simple
Linux Utility for Resource Management) is utilized. Slurm is an
open-source, fault-tolerant, and highly scalable job scheduler,
responsible for three main functions: Allocating exclusive or
non-exclusive access to resources/nodes for users, providing a
framework to initiate, execute, and monitor the work on the set of
allocated nodes and managing a queue of pending jobs \cite{yoo2003slurm}.

Interaction with Slurm is typically performed through shell scripts
written in the BASH language. These scripts contain preprocessing
directives that specify resource requirements, such as the number of
nodes, tasks per node, and execution time limit, enabling the
automation and reproducibility of computational experiments.

** COMMENT Related Work and Motivation
\label{sec.relatedwork}

** Methods and Materials

*** Software Management and Reproducibility

Reproducibility of computational experiments is a critical challenge
in computer science. To mitigate software dependency issues, the use
of the GNU Guix package manager was explored. Guix implements the
functional package management paradigm where each package is
installed in a unique and immutable directory in the store, derived
from a cryptographic hash of its dependencies \cite{courtes2013guix}.

However, the efficient training of deep neural networks using
TensorFlow requires the use of proprietary NVIDIA hardware
acceleration libraries, which are not officially distributed in
standard Guix channels due to its strict Free Software policy.

Given this restriction, the strategy adopted in this work is the use
of Python Virtual Environment for environment management. Although a
functional version of Guix exists on GitHub without the proprietary
libraries.

For managing the specific Deep Learning libraries, the python package
manager =pip= with version 25.3 was utilized. The exact version of the used library was
frozen and documented using the =pip freeze command=, generating a
requirements file (=reqs.txt=) that enables the reconstruction of the
execution environment used in the experiments.

*** Hardware and Software Configuration

The experiments were run using TensorFlow 2.15 as newer versions
showed errors when trying to train using more than one node with the
=.fit= and =MultiWorkerMirrodStrategy= and python 3.11.2. The NVIDIA
drivers version was 550.54.15 and CUDA 12.4. We used up to three
computational nodes connected with a network of 1G, each node contains an
Intel(R) Core(TM) i7-14700KF processor at 3.40 GHz with 28 threads and
20 cores, 96 GB DDR5 RAM and NVIDIA GeForce RTX 4070 with 8GB memory
accelerator.

*** Design of Experiments (DoE)

We selected two different Deep Learning models to train: *ResNet50*
\cite{resnet} as a big model with ~25.6M parameters and
*EfficientNetB0*\cite{efficientNet} as a small model with ~5.3M
parameters. The two networks were trained using the TinyImageNet-200,
a subset of the ImageNet\cite{imagenet} containing 100000 downsized to a 64×64
colored image divided among 200 classes. We created a full factorial
for each model with varying batch size and the number of nodes
used. The levels for the batch size factor were 32, 64 and 100 and for the
nodes we trained with 1, 2 and 3 nodes. Our output variable was the
training time (full training time and time per epoch).


** Challenges
Multi-node communication faced a bottleneck as the node \texttt{poti4}
was connected with a limited bandwidth of 100 Mbps. Regarding software
management, GNU Guix does not natively support proprietary libraries
due to its strict policy requiring free and open-source software.
** Results
** Conclusion
** Acknowledgments                                                  :ignore:

#+LATEX:\section*{Acknowledgements}
We would like to express our gratitude to Professor Dr. Lucas Mello
Schnorr for his guidance and the valuable insights shared regarding
performance analysis.  We also would like to thank the PCAD at
INF/UFRGS for making infrastructure and hardware used in the
experiments available.

** References                                                        :ignore:

# See next section to understand how refs.bib file is created.

#+LATEX: \bibliographystyle{ACM-Reference-Format}
#+LATEX: \bibliography{refs}


* Bib file is here                                                 :noexport:

Tangle this file with C-c C-v t

#+begin_src bib :tangle refs.bib


@inproceedings{tensorflow2016,
  author    = {Abadi, Mart\'{i}n and Barham, Paul and Chen, Jianmin and Chen, Zhifeng and Davis, Andy and Dean, Jeffrey and Devin, Matthieu and Ghemawat, Sanjay and Irving, Geoffrey and Isard, Michael and Kudlur, Manjunath and Levenberg, Josh and Monga, Rajat and Moore, Sherry and Murray, Derek G. and Steiner, Benoit and Tucker, Paul and Vasudevan, Vijay and Warden, Pete and Wicke, Martin and Yu, Yuan and Zheng, Xiaoqiang},
  title     = {TensorFlow: A System for Large-Scale Machine Learning},
  booktitle = {Proceedings of the 12th USENIX Symposium on Operating Systems Design and Implementation (OSDI '16)},
  year      = {2016},
  publisher = {USENIX Association},
}

@inproceedings{yoo2003slurm,
  title={SLURM: Simple Linux Utility for Resource Management},
  author={Yoo, Andy B. and Jette, Morris A. and Grondona, Mark},
  booktitle={Job Scheduling Strategies for Parallel Processing},
  pages={44--60},
  year={2003},
  publisher={Springer},
  doi={10.1007/10968987_3}
}

@inproceedings{courtes2013guix,
  title={Functional Package Management with Guix},
  author={Court{\`e}s, Ludovic},
  booktitle={Proceedings of the 6th European Lisp Symposium (ELS)},
  pages={15--28},
  year={2013},
  url={https://arxiv.org/abs/1305.4584}
}

@article{efficientNet,
  author       = {Mingxing Tan and
                  Quoc V. Le},
  title        = {EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks},
  journal      = {CoRR},
  volume       = {abs/1905.11946},
  year         = {2019},
  url          = {http://arxiv.org/abs/1905.11946},
  eprinttype    = {arXiv},
  eprint       = {1905.11946},
  timestamp    = {Mon, 03 Jun 2019 13:42:33 +0200},
  biburl       = {https://dblp.org/rec/journals/corr/abs-1905-11946.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

@article{resnet,
  author       = {Kaiming He and
                  Xiangyu Zhang and
                  Shaoqing Ren and
                  Jian Sun},
  title        = {Deep Residual Learning for Image Recognition},
  journal      = {CoRR},
  volume       = {abs/1512.03385},
  year         = {2015},
  url          = {http://arxiv.org/abs/1512.03385},
  eprinttype    = {arXiv},
  eprint       = {1512.03385},
  timestamp    = {Wed, 25 Jan 2023 11:01:16 +0100},
  biburl       = {https://dblp.org/rec/journals/corr/HeZRS15.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

@inproceedings{imagenet,
  title={Imagenet: A large-scale hierarchical image database},
  author={Deng, Jia and Dong, Wei and Socher, Richard and Li, Li-Jia and Li, Kai and Fei-Fei, Li},
  booktitle={2009 IEEE conference on computer vision and pattern recognition},
  pages={248--255},
  year={2009},
  organization={Ieee}
}

@misc{distributed,
  author = {TensorFlow Documentation},
  title = {Distributed training with Keras},
  year=2023,
  howpublished = {\url{https://www.tensorflow.org/tutorials/distribute/keras}},
  note = {Accessed: 2025-11-30}
}

#+end_src
* Emacs setup                                                      :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# eval: (add-to-list 'org-latex-classes '("ACMART" "\\documentclass{acmart}" ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}") ("\\paragraph{%s}" . "\\paragraph*{%s}") ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:
