# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Title (appears only in the PDF properties)
#+AUTHOR: Lucas Mello Schnorr

#+STARTUP: overview indent
#+LANGUAGE: pt-br
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_CLASS: ACMART
#+LATEX_CLASS_OPTIONS: [format=acmsmall, review=false, screen=true]
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).
# You'll also need to install texlive-publishers to get acmart.cls

* ACM-SMALL configuration for org export + ignore tag (Start Here) :noexport:

#+begin_src emacs-lisp :results output :session :exports both
(add-to-list 'load-path ".")
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
(add-to-list 'org-latex-classes
             '("ACMART"
               "\\documentclass{acmart}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

#+RESULTS:

* *The Paper*                                                       :ignore:
** Latex configurations                                             :ignore:
#+BEGIN_EXPORT latex
% Metadata Information
\acmJournal{TOMPECS}
\acmVolume{9}
\acmNumber{4}
\acmArticle{39}
\acmYear{2010}
\acmMonth{3}
\copyrightyear{2009}
%\acmArticleSeq{9}

% Copyright
%\setcopyright{acmcopyright}
\setcopyright{acmlicensed}
%\setcopyright{rightsretained}
%\setcopyright{usgov}
%\setcopyright{usgovmixed}
%\setcopyright{cagov}
%\setcopyright{cagovmixed}

% DOI
\acmDOI{0000001.0000001}

% Paper history
\received{February 2007}
\received[revised]{March 2009}
\received[accepted]{June 2009}
#+END_EXPORT
** Frontpage                                                        :ignore:
#+BEGIN_EXPORT latex
\title[Small Title]{Evaluating Tensorflow/Keras Parallel Mechanisms for Training of Deep Leaning in a HPC cluster}

\author{Rayan Raddatz de Matos}
\affiliation{%
  \institution{Universidade Federal do Rio Grande do Sul}
  \streetaddress{Campus do Vale - Sector 4}
  \city{Porto Alegre}
  \state{RS}
  \postcode{91501-970}
  \country{Brazil}}

\author{Kenichi Brumati}
\affiliation{%
  \institution{Universidade Federal do Rio Grande do Sul}
  \streetaddress{Campus do Vale - Sector 4}
  \city{Porto Alegre}
  \state{RS}
  \postcode{91501-970}
  \country{Brazil}}


\author{Marcelo Cardoso Oliveira Gulart}
\affiliation{%
  \institution{Universidade Federal do Rio Grande do Sul}
  \streetaddress{Campus do Vale - Sector 4}
  \city{Porto Alegre}
  \state{RS}
  \postcode{91501-970}
  \country{Brazil}}

#+END_EXPORT

*** Abstract                                                       :ignore:

#+LaTeX: \begin{abstract}

Put the abstract here.

#+LaTeX: \end{abstract}

*** COMMENT ACM Code Classification                                        :ignore:
#+BEGIN_EXPORT latex
%
% The code below should be generated by the tool at
% http://dl.acm.org/ccs.cfm
% Please copy and paste the code instead of the example below.
%
\begin{CCSXML}
<ccs2012>
 <concept>
  <concept_id>10010520.10010553.10010562</concept_id>
  <concept_desc>Computer systems organization~Embedded systems</concept_desc>
  <concept_significance>500</concept_significance>
 </concept>
 <concept>
  <concept_id>10010520.10010575.10010755</concept_id>
  <concept_desc>Computer systems organization~Redundancy</concept_desc>
  <concept_significance>300</concept_significance>
 </concept>
 <concept>
  <concept_id>10010520.10010553.10010554</concept_id>
  <concept_desc>Computer systems organization~Robotics</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
 <concept>
  <concept_id>10003033.10003083.10003095</concept_id>
  <concept_desc>Networks~Network reliability</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
</ccs2012>
\end{CCSXML}

\ccsdesc[500]{Computer systems organization~Embedded systems}
\ccsdesc[300]{Computer systems organization~Redundancy}
\ccsdesc{Computer systems organization~Robotics}
\ccsdesc[100]{Networks~Network reliability}

%
% End generated code
%

#+END_EXPORT

*** Keywords, thanks                                               :ignore:
#+BEGIN_EXPORT latex
\keywords{Keyword 1, Keyword 2}
\thanks{This work is supported by ...}
#+END_EXPORT
*** Maketitle                                                      :ignore:
#+LaTeX: \maketitle
** Introduction
Na última década, o Deep Learning consolidou-se como o estado da
arte para resolução de problemas complexos, como visão computacional e
processamento de linguagem natural. Diante o avanço na
precisão dos algoritmos, observou-se um crescimento exponencial na
complexidade das arquiteturas de redes neurais e no volume dos
conjuntos de dados. Este cenário impõe uma carga computacional massiva,
tornando o treinamento de modelos robustos em uma única unidade de
processamento uma tarefa inviável em termos de tempo e recursos.

Para mitigar esses desafios, o treinamento distribuído tornou-se uma
prática padrão, com destaque para a estratégia de Data Parallelism.
Nesta abordagem, uma réplica completa do modelo é
instanciada em cada unidade de processamento, GPU ou nó, e o conjunto
de dados global é particionado em batches menores com foco local.
Embora eficaz, essa técnica introduz desafios críticos de sincronização, uma vez que
os gradientes calculados localmente devem ser agregados e comunicados
entre todos os dispositivos a cada passo de treino, tipicamente
através de operações de All-Reduce.

** Background and Experimental Context
\label{sec.context}
*** Background
\label{sec.background}
Para a realização dos experimentos deste trabalho, utilizou-se o
framework TensorFlow. Segundo seus criadores
\cite{abadi2016tensorflow}, o TensorFlow é um sistema de aprendizado
de máquina que opera em larga escala e em ambientes heterogêneos. Ele
utiliza grafos de fluxo de dados para representar a computação, o
estado compartilhado e as operações que alteram esse estado.

Essa arquitetura mapeia os nós de um grafo de fluxo de dados em muitas
máquinas num cluster e dentro de uma máquina em múltiplos
dispositivos computacionais (CPUs multicore, GPUs e TPUs). Isso
oferece flexibilidade ao desenvolvedor para experimentar novas
otimizações e algoritmos de treinamento, suportando uma variedade de
aplicações com foco em redes neurais profundas.

*** Gerenciamento de Cargas de Trabalho e Scripting
Em ambientes de computação de alto desempenho (HPC), o acesso aos
recursos computacionais compartilhados é mediado por sistemas de
gerenciamento de carga de trabalho. Neste trabalho, utiliza-se o Slurm
(\textit{Simple Linux Utility for Resource Management}). O Slurm é um
escalonador de jobs de código aberto, tolerante a falhas e altamente
escalável, responsável por três funções principais: alocar acesso
exclusivo ou não exclusivo aos recursos/nodos para os
usuários, fornece uma estrutura para iniciar, executar e monitorar o
trabalho no conjunto de nós alocados e alocar os jobs gerenciados uma fila de trabalhos
pendentes \cite{yoo2003slurm}.

A interação com o Slurm é tipicamente realizada através de
\textit{shell scripts} escritos na linguagem Bash. Esses scripts
contêm diretivas de pré-processamento que especificam os requisitos de recursos, como
número de nós, tarefas por nó e tempo limite de execução, permitindo a
automação e reprodutibilidade dos experimentos computacionais.

*** Gerenciamento de Pacotes e Reprodutibilidade
A reprodutibilidade de experimentos computacionais é um desafio
crítico em ciência da computação. Para mitigar problemas de
dependências de software, explorou-se o uso do gerenciador de pacotes
GNU Guix. O Guix implementa o paradigma de gerenciamento de pacotes
funcional \cite{courtes2013guix}, onde cada pacote é instalado em um
diretório único e imutável no \textit{store}, derivado de um hash
criptográfico de suas dependências.

No entanto, o treinamento eficiente de redes neurais profundas com
TensorFlow exige o uso de bibliotecas de aceleração de
hardware proprietárias da NVIDIA, que não são
distribuídas oficialmente nos canais padrão do Guix devido à sua
política estrita de Software Livre.

Diante dessa restrição, adotou-se neste trabalho uma estratégia
de usar o PIP para o gerenciamento de ambiente, porém existe no
github uma funcional do Guix, porém sem a bibliotecas proprietárias:

Para o gerenciamento das bibliotecas específicas de Deep Learning,
utilizou-se o gerenciador de pacotes do Python (pip).
O estado exato das versões das bibliotecas foi congelado e documentado
através do comando \texttt{pip freeze},
gerando um arquivo de requisitos (\texttt{reqs.txt}) que permite a
reconstrução do ambiente de execução. 

*** Experimental Context and Workload Details
\label{sec.setup}
**** Hardware e Ambiente Computacional
Os experimentos foram conduzidos no cluster PCAD-UFRGS. Para a
avaliação de desempenho, foram utilizados até 4 nós computacionais
interconectados por uma rede {REDE}.

Cada nó computacional possui a seguinte configuração de hardware:
- **Processador:** Intel(R) Core(TM) i7-14700KF, 3.40 GHz, 28 threads, 20 cores;
- **Memória:** 96 GB DDR5;
- **Acelerador:** NVIDIA GeForce RTX 4070 - 8GB;
- **Armazenamento:** 1.7 TB SSD, 119.2 GB NVME;
  
**** Pip freeze e bibliotecas
Para garantir a reprodutibilidade, o ambiente de software foi
instanciado via Pip Freeze e req.txt. As principais bibliotecas utilizadas foram:
- **Python:** 3?;
- **TensorFlow:** 2.15;
- **CUDA Toolkit:** CHECAR VERSAO NA POTI;
- **Drivers NVIDIA:** CHECAR DRIVER DA POTI;

**** Workload
Para o treinamento da Rede Neural Convolucional (CNN), especificamente
ResNet50 e EfficientNetB0, utilizando o conjunto de dados TinyImaginet.

Para analisar o paralelismo de dados, utilizou-se a estratégia de
distribuição `MultiWorkerMirroredStrategy` do TensorFlow, que realiza
a sincronização dos gradientes entre os nós a cada passo de
treinamento. Além disso, desenvolvemos um Custom Training Loop que
diferentemente mudamos a quantos passo ele realiza a sincronização.

Os experimentos variaram as seguintes dimensões:
- **Número de nodos:** Variando de 1 a 4, cada nó com 1 GPU;
- **Batch:** Variações de 32,64 e 100;
- **Métrica de Avaliação:** Tempo por epoca e total.
** Related Work and Motivation
\label{sec.relatedwork}

Check this paper\cite{schnorr2013visualizing} about how you need to
semantically aggregate data.

Na atualidade a computação paralela está em extremo avanço devido a
alta carga computacional e a limitação temporal de aplicações
sequenciais, diante desse fato, resolvemos analisar o paralelismo de
dados para treinamento de IA em cluster afim de analisar os fatores 
que realizam a redução de tempo em relação aos parametros da aplicação
(batch, tamanho do modelo, número de nodos).

** Your Great Contribution to Computer Science
\label{sec.proposal}

** Your Super Results
** Conclusion
** Acknowledgments                                                  :ignore:

#+LATEX:\section*{Acknowledgements}

Gostariamos de expressar nossa gratidão ao Professor Dr. Lucas Mello
Schnorr pela orientação, pelos conhecimentos compartilhados sobre
análise de desempenho.

Agradeço também a estrutura PCAD fornecida pela Universidade Federal do Rio Grande do Sul
(UFRGS) - INF pela disponibilização da infraestrutura computacional de alto
desempenho.

** References                                                        :ignore:

# See next section to understand how refs.bib file is created.

#+LATEX: \bibliographystyle{ACM-Reference-Format}
#+LATEX: \bibliography{refs}

* Bib file is here                                                 :noexport:

Tangle this file with C-c C-v t

#+begin_src bib :tangle refs.bib
@article{orgmode,
  author =	"Eric Schulte and Dan Davison and Thomas Dye and Carsten Dominik",
  title =	"A Multi-Language Computing Environment for Literate Programming and Reproducible Research",
  journal =	"J. of Stat. Soft.",
  volume =	"46",
  number =	"3",
  day =  	"25",
  year = 	"2012",
  CODEN =	"JSSOBK",
  ISSN = 	"1548-7660",
  bibdate =	"2011-10-03",
  accepted =	"2011-10-03",
  acknowledgement = "",
  submitted =	"2010-12-22",
}

@incollection{schnorr2013visualizing,
  title={Visualizing More Performance Data Than What Fits on Your Screen},
  author={Schnorr, Lucas M and Legrand, Arnaud},
  booktitle={Tools for High Performance Computing 2012},
  pages={149--162},
  year={2013},
  publisher={Springer}
}

@inproceedings{abadi2016tensorflow,
  author    = {Abadi, Mart\'{i}n and Barham, Paul and Chen, Jianmin and Chen, Zhifeng and Davis, Andy and Dean, Jeffrey and Devin, Matthieu and Ghemawat, Sanjay and Irving, Geoffrey and Isard, Michael and Kudlur, Manjunath and Levenberg, Josh and Monga, Rajat and Moore, Sherry and Murray, Derek G. and Steiner, Benoit and Tucker, Paul and Vasudevan, Vijay and Warden, Pete and Wicke, Martin and Yu, Yuan and Zheng, Xiaoqiang},
  title     = {TensorFlow: A System for Large-Scale Machine Learning},
  booktitle = {Proceedings of the 12th USENIX Symposium on Operating Systems Design and Implementation (OSDI '16)},
  year      = {2016},
  isbn      = {978-1-931971-33-1},
  pages     = {265--283},
  url       = {https://www.usenix.org/system/files/conference/osdi16/osdi16-abadi.pdf},
  publisher = {USENIX Association},
  address   = {Savannah, GA, USA},
  location  = {Savannah, GA, USA},
  month     = nov
}

@inproceedings{yoo2003slurm,
  title={SLURM: Simple Linux Utility for Resource Management},
  author={Yoo, Andy B. and Jette, Morris A. and Grondona, Mark},
  booktitle={Job Scheduling Strategies for Parallel Processing},
  pages={44--60},
  year={2003},
  publisher={Springer},
  doi={10.1007/10968987_3}
}

@inproceedings{courtes2013guix,
  title={Functional Package Management with Guix},
  author={Court{\`e}s, Ludovic},
  booktitle={Proceedings of the 6th European Lisp Symposium (ELS)},
  pages={15--28},
  year={2013},
  url={https://arxiv.org/abs/1305.4584}
}

#+end_src
* Emacs setup                                                      :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# eval: (add-to-list 'org-latex-classes '("ACMART" "\\documentclass{acmart}" ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}") ("\\subsubsection{%s}" . "\\subsubsection*{%s}") ("\\paragraph{%s}" . "\\paragraph*{%s}") ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# End:
